name: "Release Generator"
description: "Generate a Github release with the name 'v[YEAR].[MONTH].[NUMBER]'"
author: "maxnowack"
inputs:
  token:
    description: "The token to access Github's API"
    required: true
  badwords:
    description: "Comma separated list of badwords for filtering commits"
    required: false
outputs: {}
runs:
  using: "node12"
  main: "dist/index.js"
