name: "Release Generator"
description: "Generate a Github release with the name 'v[YEAR].[MONTH].[NUMBER]'"
author: "maxnowack"
inputs:
  token:
    description: "The token to access Github's API"
    required: true
  badwords:
    description: "Comma separated list of badwords for filtering commits"
    required: false
  sortCommitsByMessage:
    description: "Indicates wether to sort commits alphabetically instead of by date"
    required: false
  branch:
    description: "The base branch of the repository. Defaults to your configured default branch"
    required: false
  ref:
    description: "The ref to create the release from. Defaults to the base branch"
    required: false
  useNameFromRef:
    description: "Indicates wether to use the ref as the release name"
    required: false
outputs: {}
runs:
  using: "node12"
  main: "dist/index.js"
